### ISSUE TITLE
Cannot adjust BRAW metadata after import

### ISSUE THREAD

**Issue by markspen** [latenitefilms/BRAWToolbox#1]
After opening the synchronized clip, the video inspector shows all the BRAW controls.

After clicking "Refresh Metadata" I was able to change Exposure, Color Temp, and Tint; however I could not change ISO (drop down menu appears but no matter what I select, it stays at 100), or any other parameters either like gamma and gamut cannot be changed.

2022 M1 MacBook Pro running Ventura 13.1 and FCP 10.6.5

**Comment by latenitefilms** [comment]
Thanks heaps for testing!

Currently the Final Cut Pro Inspector is a bit temperamental- try clicking the "Refresh Metadata" again until it works.

I'm trying to work with Apple to find a way to remove the "Refresh Metadata" button completely.

**Comment by latenitefilms** [comment]
This will be fixed in the next public beta. I've also simplified things, so there's less clicking:

<img width="594" alt="image" src="https://user-images.githubusercontent.com/22286696/209817206-aaa75e88-f2d2-4d47-9a56-e1677551fe2e.png">

I'm going to close this issue for now. I'm hoping the new beta will be out sometime next week if all goes to plan.
