### ISSUE TITLE
Retiming or reversing clips, stabilization option missing

### ISSUE THREAD

**Issue by MauiMoken** [latenitefilms/BRAWToolbox#106]
I often shoot certain clips in 4k 60 and retime (conform) them to my 30 or 24 fps project timeline.  I also occasionally reverse a clip to get an alternate slider move if it suits the sequence and other times I'll speed up footage for quick timelapse effects.  It appears that retiming is not possible with the Braw clips now using the extension in FCP.  If I do retime a clip in the timeline using the normal retime editor like anything I described above, I do see the effect but in the footage but it does not render. (red line over a section of footage, skipping playback) 

I also noticed that Stabilization is no longer an option in the inspector.  

Q: Are these all still options with Braw in FCPx, if so what is the workaround?

Thanks
<img width="967" alt="Screen Shot 2023-03-29 at 1 11 29 PM" src="https://user-images.githubusercontent.com/129340340/228688202-d94414c9-7c23-4fec-93f3-ac8382f4d135.png">

**Comment by latenitefilms** [comment]
Apologies for the delayed reply!

Retimes and speed effects should all work correctly. The red line is a weird one - we've been chatting with the Final Cut Pro team about this for a while, but they haven't come back to us with a definite cause, fix or workaround. In theory it's just a debugging tool, so it shouldn't have any impact, but generally speaking if you see it - it means FCPX is doing weird things.

Can you try importing your BRAW files as Multicam Clips instead of Synchronised Clips and see if that has any impact?

See: 

https://brawtoolbox.io/faq/#i-dont-like-synchronised-clips-can-i-import-a-multicam-clips-instead

Regarding stabilisation see:

https://brawtoolbox.io/stabilisation/

**Comment by MauiMoken** [comment]
Chris, Thanks very much for detailed breakdown. It does appear to render out properly when retiming so it seems to function just fine even the red line fcpx glitch. Understood on the stabilization. Thank you. Great tool, can’t wait to dig my Bmpcc out of the closet and put it back to work. Cheers, Travis Sent from my iPhoneOn Apr 2, 2023, at 1:30 AM, Chris Hocking ***@***.***> wrote:﻿
Apologies for the delayed reply!
Retimes and speed effects should all work correctly. The red line is a weird one - we've been chatting with the Final Cut Pro team about this for a while, but they haven't come back to us with a definite cause, fix or workaround. In theory it's just a debugging tool, so it shouldn't have any impact, but generally speaking if you see it - it means FCPX is doing weird things.
Can you try importing your BRAW files as Multicam Clips instead of Synchronised Clips and see if that has any impact?
See:
https://brawtoolbox.io/faq/#i-dont-like-synchronised-clips-can-i-import-a-multicam-clips-instead
Regarding stabilisation see:
https://brawtoolbox.io/stabilisation/
