### ISSUE TITLE
Possible maths bug when cutting a clip?

### ISSUE THREAD

**Issue by latenitefilms** [latenitefilms/BRAWToolbox#11]
Marco Iorio writes via TestFlight:

> If I blade a clip in the storyline and then delete the bladed clip, audio is ok, but video is out of sync and it plays back "something" which is not the remnant of the bladed clip.

I'm ASSUMING Marco is actually blading the clip WITHIN the synchronised clip, but if he's not, and he's blading the synchronised clip within a project, then it's most likely a maths bug.

**Comment by Marco-Iorio** [comment]
I mostly edit surgical videos. Most of my editing is cutting “dead time” from the surgery, leaving only what really matters, so my workflow is:
- import the media
- Put it all in the storyline 
- Play it and use ctrl-B to cut out the useless parts.
- Stitch together what’s left
- Put some cross-dissolve
- Make color corrections if needed
- Export
Quite simple. 
The issue comes with the ctrl-B in the storyline. 
If I highlight part of the footage and drag just the part of the clip in the storyline it works as expected. 
I hope it’s clearer now.

**Comment by latenitefilms** [comment]
Legend, thanks for the detailed reply!

Just to confirm, you're dragging the Synchronised Clip from the "🔥 FROM BRAW TOOLBOX" event into your timeline?

Does your project/timeline frame rate match your clip frame rate?

Are you able to share a screenshot of your timeline?

I've just tried throwing in a bunch of test clips, and I can't reproduce the issue:

<img width="920" alt="image" src="https://user-images.githubusercontent.com/22286696/210280869-c5887a51-f8f1-4e18-8054-87b3be0f7aa9.png">

**Comment by latenitefilms** [comment]
I'm going to close this issue for now, but please re-open it if you're still having issues with Public Beta 2. Thanks!
