### ISSUE TITLE
BRAW Plug-in not responding

### ISSUE THREAD

**Issue by t3dc** [latenitefilms/BRAWToolbox#148]
This appears to be related to [this discussion](https://github.com/latenitefilms/BRAWToolbox/discussions/146).

We just recently migrated our edit from temporary storage to our main edit suite. Initial relinking of the braw files went fine, but then the files started showing red again. Trying to relink a second time hangs as BRAW Toolbox is reading initial files.

However, if I create a new library and add the files from scratch everything works fine. That just means losing several days of work. Is there a solution to this besides just starting over?

Here's the error from the logs:

`2023-07-27 09:56:53.326 BRAW Toolbox Renderer[1187:65923] [BRAW Toolbox Renderer] Showing early error message: MissingBRAWFileNilBookmark
/AppleInternal/Library/BuildRoots/d9889869-120b-11ee-b796-7a03568b17ac/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShaders/MPSImage/Filters/MPSImageUnaryKernel.mm:354: failed assertion `Destination 0x7fde0ea0c550 texture format 81  must be writable.
'`

It manifests on screen like this:

![Screenshot 2023-07-27 at 09 43 52](https://github.com/latenitefilms/BRAWToolbox/assets/52919338/8d7d8f38-869f-4f45-9778-703494579158)

I'm also attaching our logs as per the FAQ.

[Application Support.zip](https://github.com/latenitefilms/BRAWToolbox/files/12181410/Application.Support.zip)

I suspect we changed versions of BRAW Toolbox in our migration. The linked thread above implies a "solution" but the answer is just a thank you message without steps to resolution. Thanks for any help you can offer.

**Comment by latenitefilms** [comment]
Can you try granting sandbox access to the drive which contains your footage?

https://brawtoolbox.io/collaboration/

By granting sandbox access, BRAW Toolbox will just use the file path, rather than a security-scoped bookmark to get permission to access the BRAW files from within the applications sandbox. This should work - assuming the paths are correct. You can export a FCPXML to check manually.

Can you also please have a look in your Crash Reports folder and send any crash reports? See:

https://brawtoolbox.io/troubleshooting/#ive-run-into-a-bug-where-can-i-find-the-log-files

**Comment by t3dc** [comment]
That looks to have sorted us out! Thank you so much!
