### ISSUE TITLE
Lower quality files than reported in inspector?

### ISSUE THREAD

**Issue by FA1KFA1KFA1K** [latenitefilms/BRAWToolbox#150]
(apologies as I also emailed this to support)

Just imported 4tb of footage through the toolbox and it's really saving my bacon - thanks so much devs 🙏

My problem is that I’m finding a big difference in the reported resolution of the clips in the inspector / mac finder and the apparent resolution on the timeline, preview and on export. Almost as if I'm working with proxies which, to my knowldge, I am not!

Image data for original BRAW according to finder:
![image](https://github.com/latenitefilms/BRAWToolbox/assets/75326703/1386c1fe-b177-4b86-93c4-7ac691c31021)

Inspector on toolbox-imported clips in FCPX:
![Screenshot 2023-09-12 at 15 50 02](https://github.com/latenitefilms/BRAWToolbox/assets/75326703/37f9dee2-5f65-4fd1-90d7-9c95f6450b84)

Image quality with spatial conform set to none (this is from preview but looks the same on export!):
![Screenshot 2023-09-12 at 15 52 08](https://github.com/latenitefilms/BRAWToolbox/assets/75326703/5a9d3e93-c534-4a38-88b1-b12072540285)

Undoubtably I'm doing something stupid but any pointers hugely appreciated!

Cheers!

**Comment by FA1KFA1KFA1K** [comment]
Follow up: I don't see the BRAW Toolbox effect in the inspector view for the clips I "imported" through the toolbox extension (I understand there's meant to be the option to force full quality on export there). Do I have any options other than re-importing 4tb worth of footage as "FULL" rather than "AUTOMATIC HD"?

**Comment by latenitefilms** [comment]
I responded to the original post directly via email, but in regards to the follow up.

As explained in [How To Use](https://brawtoolbox.io/how-to-use/), to access the BRAW Toolbox effect, you need to double click on the Multicam Clip to access the Angle Editor, then double click on the first Angle to go inside that Synchronised Clip.  You'll now see a Generator on the Primary Storyline and an Audio file underneath. If you click the Generator on the Primary Storyline, you can access the BRAW Toolbox effect, including the **Global Settings** button, where you can force decoding options across ALL BRAW Toolbox clips.

Because this is a Global Setting, you could also apply the BRAW Toolbox effect manually to a disable clip on your timeline for easy access.

Hope this helps!

**Comment by FA1KFA1KFA1K** [comment]
Hi sorry Chris - I know I’m being frustrating but I didn’t import the clips as multicam - I unchecked that option (which is where I think the misunderstanding is stemming from and I totally should have said that from the start) 

So my basic q is: if my clips are imported as Automatic (HD) and multicam is unchecked on “import” is there any way for me to force my timeline to export in full quality?

Thanks for your patience!

Matt x

**Comment by latenitefilms** [comment]
That's totally fine, and the same logic applies. Just double click on the Synchronised Clip, click on the Generator then you'll find the BRAW Toolbox effect where you can change the Global Settings.

**Comment by FA1KFA1KFA1K** [comment]
Chris. I’m an imbecile.

You are a star thank you so much for this amazing plugin and your infinite patience 🙏

Matt x
