### ISSUE TITLE
Failed to startAccessingSecurityScopedResource in buttonSelectBRAWFilePressed.

### ISSUE THREAD

**Issue by OutlawMedia** [latenitefilms/BRAWToolbox#152]
After successfully important BRAW footage using the workflow extension, it seems that the connection keeps dropping out. Not sure why this is. When I apply the Effect to a clip in the timeline and then try to Select BRAW File I get this message: 

Failed to startAccessingSecurityScopedResource in buttonSelectBRAWFilePressed.

When I try to Grant Sandbox Asses using the Global Settings to the external hard drive that contains the BRAW files I get this message: 

Failed to create security-scoped bookmark due to: The file “TSL 22” couldn’t be opened.

I get the same request when I go beyond the root drive folder into the subfolder that contains the BRAW files. 

I should add that, for now, when I restart Final Cut Pro everything pops back in to place. But before long, within 30 minutes I start getting the red "Missing BRAW File" image again.

Am I missing a permission switch somewhere?

**Comment by OutlawMedia** [comment]
I should add that, for now, when I restart Final Cut Pro everything pops back in to place. But before long, within 30 minutes I start getting the red "Missing BRAW File" image again.

**Comment by latenitefilms** [comment]
I'm on the road currently, but just quickly...

You should never have to manually add the BRAW Toolbox effect, this is done by the Workflow Extension. If you use the default setting of creating a Multicam Clip, you can find the BRAW Toolbox effect by double clicking the Multicam Clip, then double clicking the first angle, and clicking on the Generator on the Primary Storyline. Generally speaking most people do all their main RAW corrections in the Workflow Extension prior to importing then only go into the Effect settings for manual adjustments as required.

This is explained here:

https://brawtoolbox.io/how-to-use/

For a slight performance improvement you can Grant Sandbox Access to the drive or drives that contain your BRAW footage. This means that Final Cut Pro can just use the BRAW file path, rather than the Security Scoped Bookmark, as it has read access to the entire drive.

This is explained here:

https://brawtoolbox.io/collaboration/

Hope this helps!

**Comment by latenitefilms** [comment]
Also... I'd suggest try restarting your Mac, open a new FCPX library, import in a single BRAW file, double click the Multicam Clip, double click the Angle, click the Generator, then in the Inspector try add the drive containing all your BRAW files via the Grant Sandbox Access menu item. Quit FCPX, then try your existing FCPX library with BRAW clips and see if it all works correctly.

Weirdly, macOS can actually run out of security scoped resources, and restarting is only way to fix.

**Comment by OutlawMedia** [comment]
Following up to say that restarting my Mac seemed to have fixed the problem. I usually don't restart it for long periods of time unless prompted to by software updates. So the limited security scoped resources must have been the root issue.

Thank you!
