### ISSUE TITLE
problem when adding braw tool box effect to clip

### ISSUE THREAD

**Issue by Sallen307** [latenitefilms/BRAWToolbox#163]
When I add BRAW Toolbox effect to clip it starts my clip from the beginning of the clip , and not from the selected cut clip. Why is this happening?

**Comment by latenitefilms** [comment]
You should NEVER manually add the BRAW Toolbox effect. The effect should always be applied via the Workflow Extension.

This is explained in more detail here: https://brawtoolbox.io/how-to-use/

**Comment by Sallen307** [comment]
Got it! Thought I was able to use it before probably. But question, why is
it there if it can’t be used ?

**Comment by latenitefilms** [comment]
The Workflow Extension applies the BRAW Toolbox effect, which is why it exists in the Effects Browser.

You can _technically_ still use it - but you'd have to use it within a Compound Clip or Synchronised Clip.

The technical reasons for this are explained in more detail here: https://github.com/latenitefilms/GyroflowToolbox/issues/8

**Comment by Sallen307** [comment]
Thank you for the clarification.
