### ISSUE TITLE
BRAW Toolbox is crashing Final Cut Pro

### ISSUE THREAD

**Issue by cschaudel** [latenitefilms/BRAWToolbox#180]
I keep trying to import the BRAW files from BRAW Toolbox. When I try to drop the files into the Library, Final Cut Pro crashes.

**Comment by latenitefilms** [comment]
Sorry you're having issues!

What version of Final Cut Pro? What version of macOS?

Does the BRAW Toolbox effect appear in the Effects panel in Final Cut Pro?

Have you following all the installation instructions [here](https://brawtoolbox.io/installation/)?

What happens if you try and manually import this FCPXML file (which is the last FCPXML that BRAW Toolbox generated)?

```
/Users/YOUR-USER-NAME-GOES-HERE/Library/Group Containers/A5HDJTY9X5.com.latenitefilms.BRAWToolbox/Library/Application Support/Last Export.fcpxml
```

Are you able to share the Final Cut Pro crash log and any BRAW Toolbox logs? Instructions [here](https://brawtoolbox.io/troubleshooting/#ive-run-into-a-bug-where-can-i-find-the-log-files).

**Comment by latenitefilms** [comment]
Closing this issue for now, feel free to re-open if you're still having issues.
