### ISSUE TITLE
Imported BRAW Clips and FCP standard features.

### ISSUE THREAD

**Issue by tangierc** [latenitefilms/BRAWToolbox#3]
First time import observations (may not be bugs)

1. Opening an imported and synced BRAW video clip does not draw the frames in the timeline. The **video clip is all black.**
2. Dragging an imported and synced BRAW clip on the timeline does yield a drawn video clip on the timeline where users can see the content of the clip.
3. **Unable to "Reveal in Browser"** from video clip inside BRAW Toolbox-generated synced clip. This feature is present.
4. With no access to original video clip in the browser, I cannot sort by creation date with other clips in my event or library that may have been shot on the same day for the purposes of making multicam clips. I only have the synced clips and their creation dates (the day using BRAW Toolbox) to work with.
5. Unable to transcode BRAW Toolbox-generated synced clips for a proxy workflow. FCP feature disabled.
6. With no access to the original standalone clip in the browser, I cannot transcode BRAW clips for a proxy-based workflow. FCP feature disabled.
7. With no access to the original standalone clip in the browser, I **cannot "Reveal in Finder"**

My specific-use case is to be able to import BRAW video clips, create multicam clips with them, and transcode them for a proxy workflow until being ready to switch back to camera original clips, though I realize that transcoding is an entirely different process than BRAW Toolbox was designed for. If I can reveal in browser and finder, that would help.

**Comment by latenitefilms** [comment]
Replies below:

> 1. Opening an imported and synced BRAW video clip does not draw the frames in the timeline. The video clip is all black.

The Synchronised Clip created by BRAW Toolbox should display thumbnails in the timeline:

<img width="1823" alt="image" src="https://user-images.githubusercontent.com/22286696/209415587-fb07aa9f-f23b-4d21-9ae1-71efa165fb45.png">

If you "go inside" the Synchronised Clip, the Video Clip won't have thumbnails. Annoyingly, Final Cut Pro doesn't update thumbnails for Generators. However, as you'll be working with the Synchronised Clip anyway, this shouldn't be an issue.

> 2. Dragging an imported and synced BRAW clip on the timeline does yield a drawn video clip on the timeline where users can see the content of the clip.

The idea is that users will only really ever use the Synchronised Clips.

> 3. Unable to "Reveal in Browser" from video clip inside BRAW Toolbox-generated synced clip. This feature is present.

You should be able to "Reveal in Browser" on the Synchronised Clip.

<img width="1914" alt="image" src="https://user-images.githubusercontent.com/22286696/209415673-a6afc69d-167b-4f0c-9c58-3a45815d58aa.png">

If you "go inside" the Synchronised Clip, you won't be able to "Reveal in Browser" on the Video Clip, because this clip is just a generator in the Synchronised Clip, and doesn't actually exist in the Browser.

> 4. With no access to original video clip in the browser, I cannot sort by creation date with other clips in my event or library that may have been shot on the same day for the purposes of making multicam clips. I only have the synced clips and their creation dates (the day using BRAW Toolbox) to work with.

The plan is basically that you'll only ever work with the Synchronised Clip's - however, good point about the Creation Date.  In the next beta, we'll update the Creation Date of the Synchronised Clip to match the BRAW file.

> 5. Unable to transcode BRAW Toolbox-generated synced clips for a proxy workflow. FCP feature disabled.

Unfortunately this is a FCPX limitation. You could workaround this by just selecting all the clips in the Browser and exporting from there. We'll be adding something to the Toolbox within the Workflow Extension to relink from BRAW files to MOVs.

> 6. With no access to the original standalone clip in the browser, I cannot transcode BRAW clips for a proxy-based workflow. FCP feature disabled.

Same answer as 5.

> 7. With no access to the original standalone clip in the browser, I cannot "Reveal in Finder"

Again, the idea is that users will only really ever use the Synchronised Clips.

Hope this helps! Any questions let me know!

**Comment by tangierc** [comment]
Thanks Chris. I understand all of the comments. My hope was to have access to just the video clips without them being synced so that I can make manipulate them on my own within FCP (make multicam clips, sort, transcode etc.)

I appreciate all of the work you've done.  

One potential enhancement could be to have a status bar or some other visual to represent the "Prepare BRAW Files" process. I only knew that activity was happening by watching the lights flashing on my RAID and hearing the drives working.

**Comment by latenitefilms** [comment]
You can still make multi-cam clips with the Synchronised Clips. A lot of people will be doing dual system audio anyway, so most of the time they'll be using something like Sync-N-Link to combine the BRAW Synchronised Clips with location audio.

The reason they're a synchronised clip is really just to combine the visuals and audio together. Even if I'm not syncing audio or using multiple angles, I'd still probably turn them into multicam clips, for grading purposes, etc.
