### ISSUE TITLE
Progress bar disappears during playback

### ISSUE THREAD

**Issue by JW144754** [latenitefilms/BRAWToolbox#6]
See attached Screen recording, the progress bar disappears when hitting "play", then reappears when playback stops.

https://user-images.githubusercontent.com/72329359/209752790-eb1b2a35-d2f6-471d-98cb-a33f2caf1cf3.mov

**Comment by latenitefilms** [comment]
This is currently deliberate, as I didn't want to waste resources updating the progress bar during playback, but I will have another look into this if it's confusing, and see if there's a way I can make it work.

**Comment by JW144754** [comment]
That makes sense. It was only initially confusing, since the viewer is relatively small...I was testing with my 6k wide angle of a concerthall, which I could barely see if there were movements or not. It's probably something worth looking into later in the stage.

Also, might this compound clip workflow works for Gyroflow Toolbox, to avoid the FxPlug timecode issue? I can see it complicates things too, but considering that's the current workaround anyway... Just a thought.

**Comment by JW144754** [comment]
Also, on this topic, two suggestions for future consideration:

1. make the viewer in Toolbox plugin extension resizable?
2. have some way of showing progress percentage after clicking "Prepare BRAW files", because if I am working with a large and long cip (2hr continuous 6k concert recording), it takes sometime to generate the audio file, during which without a progress indication, it just looks like the plugin has frozen and might confuse some people.

**Comment by latenitefilms** [comment]
> Also, might this compound clip workflow works for Gyroflow Toolbox, to avoid the FxPlug timecode issue? I can see it 
complicates things too, but considering that's the current workaround anyway... Just a thought.

We would have to make a Workflow Extension for Gyroflow Toolbox, but I feel like that would be more annoying for the end user anyway. I think the basic rule will just have to be "apply it to the entire clip" - until Apple comes up with a fix.

> Also, on this topic, here is something that I know you have thought about already and will make it happen even without me saying, but make the viewer in Toolbox plugin extension resizable?

If you resize the Workflow Extension, the Viewer will get bigger too.

> Have you also considered integrating this plugin into CommandPost? Just a thought, same as the Gyroflow Toolbox? CommandPost is just such an amazing one-stop shop to take fcp to the next level already.

Gyroflow Toolbox code can't touch CommandPost code due to licensing issues. Gyroflow Toolbox will have to be its own standalone product. The only reason I really started looking into Gyroflow, was to add gyro stabilisation for BRAW files, but sadly I can't build this into BRAW Toolbox directly, due to licensing.

BRAW Toolbox is currently closed-source. I MIGHT open-source it after public release, but we'll see. BRAW Toolbox will most likely be eventually sold on the Mac App Store.

**Comment by JW144754** [comment]
> If you resize the Workflow Extension, the Viewer will get bigger too.
> > I am not sure if I am doing this wrong again, but mine is not doing that.



https://user-images.githubusercontent.com/72329359/209979081-4570adb9-d00c-471f-a5ac-99fcdd89f068.mov

**Comment by latenitefilms** [comment]
This will be fixed in the next beta.
