### ISSUE TITLE
Automatic Speed breaks Braw toolbox

### ISSUE THREAD

**Issue by Tothemaxrelax** [latenitefilms/BRAWToolbox#65]
When i place automatic speed on any braw clip in a project and then adjust the speed the video becomes a freeze frame and breaks the braw clip.

**Comment by latenitefilms** [comment]
Automatic Speed shouldn't really do anything - it should always just play at 100%, because the BRAW Toolbox clips are just dumb Generators. FCPX has no knowledge of the BRAW files "original" speed. 

When I click on **Automatic Speed** for a BRAW clip here, it doesn't do anything - it remains at 100%, which is expected:

![image](https://user-images.githubusercontent.com/22286696/216480442-c6dbb3f5-b1a6-4e82-91f6-c1e8b454b8d8.png)
