### ISSUE TITLE
Decode Quality Dropdown in Final Cut Pro Inspector Bug

### ISSUE THREAD

**Issue by JW144754** [latenitefilms/BRAWToolbox#7]
I might be doing something wrong here, but the Decode Quality does not seem to effect anything? I just tested with one of my 6k clips from my bmpcc6k, and ringing through Toolbox, I have set the Decode Quality option to Full, and UltraHD (in two different tests. Then after importing it into FCP and using it in a 4k timeline, the playback quality does not look like the 6k resolution at all. It seems to be playing back at 1080p max, or even worse? Exporting the project in 4k also shows the same blurry result.

In FCP inspector, both the compound clip and the video clip within shows the correct 6134*3456 resolution, but again, it does not look like that in the viewer or exporting.

**Comment by latenitefilms** [comment]
Are you adjusting the decode quality in the Workflow Extension or the Final Cut Pro Inspector?

**Comment by JW144754** [comment]
In the workflow extension forst, then the inspector. I have tried multiple combinations.

**Comment by latenitefilms** [comment]
I'm assuming you have "Better Quality" selected in the Final Cut Pro Viewer?

I'll do some more digging into this later. It's entirely possible there's a bug that's causing us to not set the Decode Quality correctly, or there's some funkiness in terms of scaling within Final Cut Pro.

In the next beta we'll also have some "Global Settings", so that you can force everything to "Full Decode Quality" prior to exporting, if you're working with 6K or 8K, etc.

**Comment by JW144754** [comment]
Yes I have changed between better performance and better quality, also the reason I did a 4k export just to make sure it wasn't a playback issue only.

**Comment by latenitefilms** [comment]
There was a bug, all the menu items in the Final Cut Pro Inspector were off by one, so if you have "Full" selected, it would actually do "Half". This will be fixed in the next beta. Thanks for reporting!

**Comment by latenitefilms** [comment]
This is what the revised Final Cut Pro Inspector currently looks like:

<img width="586" alt="image" src="https://user-images.githubusercontent.com/22286696/209816924-5b06d381-7067-45f2-b6aa-561ab2849b7c.png">

These "Global Settings" allow you to override the individual clip "Decode Quality" settings - so that you can edit at a lower quality Decode Quality, then bump it up to Full for export.

I'm going to close this issue for now.
