### ISSUE TITLE
Speeding clips and reversing doesn't work

### ISSUE THREAD

**Issue by thadeuszT** [latenitefilms/BRAWToolbox#71]
Just tried to use my clips - shot BRAW 120fps 2.8K, but in an 2.8K/25p clip format. FCPX Sequence is 25p HD. Imports fine, but doesn't play (or only sometimes), when speeding up. Hope, this can be fixed...

MBP 2022, 16GB, 1TB, Mac OS 12.6.3, FCP 10.6.5

**Comment by latenitefilms** [comment]
I can't reproduce, but someone else ran into this. They said they got it working by turning into a Compound Clip before doing any speed effects. It sounds like it's a Final Cut Pro bug rather than anything we can fix.

Can you try that? Alternatively, you can try making Multicam clips instead of Synchronised Clips and see if that helps?

https://brawtoolbox.io/faq/#i-dont-like-synchronised-clips-can-i-import-a-multicam-clips-instead

**Comment by thadeuszT** [comment]
Ah, ok. That works. Good to know. Thanks!
