### ISSUE TITLE
Retiming clips

### ISSUE THREAD

**Issue by EnlightenedImages** [latenitefilms/BRAWToolbox#72]
Retiming clips in FCP isn't supported.

**Comment by latenitefilms** [comment]
This seems to be a bug with Final Cut Pro and Synchronised Clips in some cases. We're contacting the Final Cut Pro team to try and resolve.

Try turning it into a Compound Clip first, or create Multicam Clips in BRAW Toolbox rather than Synchronised Clips.

See: https://brawtoolbox.io/faq/#i-dont-like-synchronised-clips-can-i-import-a-multicam-clips-instead

**Comment by EnlightenedImages** [comment]
Thanks Chris!  Would the same technique apply for Trim Tool?  There is no change to the clip when using Trim Tool.

Really liking your software otherwise.

Thanks
Carlos

**Comment by latenitefilms** [comment]
We haven't had any other reports of issues with the trim tool, but yes, in general, for SOME types of BRAW clips, Final Cut Pro seems to work much better with Multicam Clips rather than Synchronised Clips, even though inside the Multicam Clip is just a Synchronised Clip anyway. 

Just make sure you're not trimming the generator that lives INSIDE the Synchronised Clip, as trimming or cutting that won't work. You should always just bring your Synchronised Clip or Multicam Clip into a timeline/project first.
