### ISSUE TITLE
Beggining of clip never plays always a freeze frame

### ISSUE THREAD

**Issue by gcowie85** [latenitefilms/BRAWToolbox#75]
When I bring the clips into my timeline the first 15 seconds or so is always a freeze frame. It won't play the very begging of the clip I have to go about 20 seconds in for it to start playing. It will play in the preview section but not in the timeline. It doesn't matter if I change the start point to later on, it then does it at that start point. Please help me fix this.

**Comment by latenitefilms** [comment]
As discussed via email, as a first step, I'd try downloading the [v1.0.1 beta from TestFlight](https://github.com/latenitefilms/BRAWToolbox/discussions/74) to see if that has any impact.

As you'll see in the [release notes](https://brawtoolbox.io/release-notes/) there's a lot of general enhancements and improvements, so that's a good starting point.

I'd also suggest trying to use Multicam Clips instead of Synchronised Clips, as Final Cut Pro seems to work better with those (even though the Multicam Clip just contains the exact same Synchronised Clip). See instructions [here](https://brawtoolbox.io/faq/#i-dont-like-synchronised-clips-can-i-import-a-multicam-clips-instead).

I'll close this issue for now, but feel free to re-open and add comments if none of the above helps!

**Comment by gcowie85** [comment]
I tried just switching the import to Multicam Clips like you suggested and this worked. Thank you.
