### ISSUE TITLE
Unwanted behaviour with Slipping and Extending clips on timeline

### ISSUE THREAD

**Issue by thermidorthelobster** [latenitefilms/BRAWToolbox#84]
A couple of issues I've spotted this evening:

1) When Slipping a clip on the timeline with the Trim tool, although FCPX showed the in / out times changing, the same BRAW video would render regardless of having Slipped the clip.

2) When Extending a clip on the timeline by dragging its In handle leftwards, I then got a clip which looped! For a single clip in the timeline, BRAW Toolbox renders a portion of that clip, then renders it again. Restarting FCPX did not get rid of this behaviour, and oddly, recreating the In and Out points in the browser and dragging the clip back onto the timeline doesn't fix the looping. The clip previews fine in the browser but won't play correctly on the timeline.

**Comment by latenitefilms** [comment]
Are you running the latest v1.0.2 BRAW Toolbox release on Final Cut Pro 10.6.5? What version of macOS?

Just to confirm, you're definitely dragging the Synchronised Clip or Multicam clip from the Browser to a new project/timeline, correct? You shouldn't ever modify the "insides" of the Synchronised Clip, as that's just a Custom Generator with the BRAW Toolbox effect applied to it - so you can't cut or trim it.

Whilst I haven't been able to reproduce this problem, we have seen a few users have funky issues like this when dealing with speed effects, etc. and they found that converting the clip into a compound clip would fix things, etc. so it seems to be bugs in Final Cut Pro, rather than anything specific to BRAW Toolbox.

Essentially, if everything is looking correct in the browser when you skim the Synchronised Clip or Multicam clip, then it should all work the same/correctly when you import into a project/timeline.

I'd suggest trying to create Multicam Clips instead of Synchronised Clips via BRAW Toolbox, and see if that makes any difference. Generally speaking, Final Cut Pro seems to be a bit more unreliable with Synchronised Clips, whereas Multicam Clips are generally pretty rock solid.

See: https://brawtoolbox.io/faq/#i-dont-like-synchronised-clips-can-i-import-a-multicam-clips-instead

If you're still having issues, are you able to do a screen recording to demonstrate what you're seeing?

**Comment by thermidorthelobster** [comment]
This is FCPX 10.6.5 on Ventura 13.2 with BRAW Toolbox 1.0.2. I’m definitely
not playing with the internals of the sync clip; just viewing the sync clip
in its entirety in the Browser and editing onto the timeline as normal.
Just tried creating a CC, which didn’t fix the repeating issue, but then
noticed that this clip in the Browser does have this weird repetition thing
right at the beginning - but not in the section that (according to the red
Used Media line) is what’s sitting on the timeline. Very odd.

So then I tried re-importing that clip as Multicam instead of Sync Clip and
the same thing happens. It repeats a section. Difficult to tell exactly
what’s happening when as the bloody background is black, so half the time
there’s nothing to see, but it’s definitely repeating.

The preview in BRAW Toolbox before I import seems to play the clip without
issue.

I’ll send you the BRAW file, and what it looks like off the timeline, and
you can see if it does the same for you!

**Comment by latenitefilms** [comment]
That file you sent me seems a bit... weird. When I open in the Blackmagic RAW Player and press play, it jumps from 00:50:47:23 to 00:50:48:15, then starts playing. 

However, playing in DaVinci Resolve seems to work fine. I also tried importing into BRAW Toolbox, and it all seems to behaving correctly for me? I tried exporting it, and it looks correct for me too. I'm definitely not seeing what you're seeing in the "oddly behaved clip exported from timeline" export. Weird!

I'll share that clip with some engineers at Blackmagic and see if they have any ideas.

Unrelated, make sure you update to Ventura 13.2.1 as that fixes some other AppKit-related bugs:

https://twitter.com/FCPdotCO/status/1625209366482718726

**Comment by latenitefilms** [comment]
Blackmagic are also seeing some weirdness with that clip. They're going to discuss internally with their Blackmagic RAW engineers.

Will let you know if I hear anything more.

**Comment by latenitefilms** [comment]
Unfortunately I haven't heard anything more specifically about this file/bug from Blackmagic, apart from confirmation that something went funky with the recording - so I'm assuming this was just a dodgy file - maybe there were dropped frames, or maybe something happened to the camera when it was finalising the file?

I'm going to close this issue for now, under the assumption that this was an issue specific to that dodgy BRAW file, but feel free to re-open the issue if you disagree or have more information/insight.
