### ISSUE TITLE
Problem with cut.

### ISSUE THREAD

**Issue by Ste5corde** [latenitefilms/BRAWToolbox#89]
When I go to a timeline to make a cut it goes out sink! This makes it impossible to work. The problem doesn't always occur, but if I cut on the same point and it goes out of the sink, maybe I do a cmd + z and redo the cut, the problem disappears.

**Comment by latenitefilms** [comment]
Thanks for reaching out @Ste5corde - and sorry to hear you're having issues!

I assume you're using the latest v1.0.4 release on the Mac App Store, and using Final Cut Pro v10.6.5? If you're using macOS Ventura, make sure you're using the latest update, as there was a bug in v13.2 that caused issues with Final Cut Pro - discussed [here](https://github.com/CommandPost/FinalCutPro/issues/86).

If the Synchronised Clip (or Multicam Clip) is playing correctly in the browser, and is working as expected most of the time in the Timeline, but somethings doing weird things - then it sounds like some kind of bug/issue in Final Cut Pro itself, rather than anything in BRAW Toolbox specifically.

You can try trashing Final Cut Pro's preferences files, and see if that has any impact?

Two things you can try that may or may not have any impact are granting the drive that contains all your BRAW footage sandbox access. This has a very slight performance benefit, as it means Final Cut Pro doesn't need to "convert" the security-scoped bookmark into a file path for each frame. You can find instructions on how to do this [here](https://brawtoolbox.io/collaboration/).

The other thing you can try is creating Multicam Clips instead of Synchronised Clips - as generally speaking, Synchronised Clips are always a little bit more weird and unreliable in Final Cut Pro. You can find instructions on how to do this [here](https://brawtoolbox.io/faq/#i-dont-like-synchronised-clips-can-i-import-a-multicam-clips-instead).

Let me know if you're still running into issues!
